### ISSUE TITLE
Issue with page memo list

### ISSUE THREAD

**Issue by rayman89** [wildskyf/pageMemo#10]
When clicking on the page memo list it opens a blank new tab or sometimes it opens a new tab with this moz-extension://f7029f57-c305-47ef-8a30-9546d038d668/myanimelist.net/anime/1573/Kishin_Douji_Zenki  for example instead of loading the url of the page memo..

BTW it would be nice if you could open the list of page memos on right click.  (I'm runing out of space on the browser for buttons XD)

Something like this 
![imagen](https://user-images.githubusercontent.com/5449042/29038339-ec74fbcc-7b6c-11e7-8741-71c492d6abf0.png)

**Comment by wildskyf** [comment]
Hi @rayman89 ,

Thank you for your report, I will fix that soon :)

And I have open another issue for your BTW #11 
It will be apply soon, too. :)
