### ISSUE TITLE
Export/Import stickies

### ISSUE THREAD

**Issue by rayman89** [wildskyf/pageMemo#13]
Could you add a feature to export and import stickies for when we wanna port the stickies to an other pc/profile?

**Comment by wildskyf** [comment]
Good idea! I will implement it soon.

Thanks for your idea. :)

**Comment by rayman89** [comment]
any progress on this?

**Comment by wildskyf** [comment]
@rayman89 sorry, I am too busy recently...
I hope I could implement it on this weekend!
Thanks for your patient!!!

**Comment by wildskyf** [comment]
Hi @rayman89 
I just upload v1.15.0
You could go to the preference page of pageMemo, and you will find the "import/export" function there!
Sorry for my long delay, and thx for your reminder. :)

Enjoy it!


If you find any bugs or want to provide some suggestions about this function, feel free to reopen this issue or just comment below.

**Comment by rayman89** [comment]
I tested it and It all seems to be working perfectly thanks  a lot.
