### ISSUE TITLE
Changing color makes note not able to become translucent

### ISSUE THREAD

**Issue by rayman89** [wildskyf/pageMemo#14]
Changing color makes note not able to become translucent when not focused. Also if you could make the transparency a little less transparent it would be perfect.

**Comment by wildskyf** [comment]
workaround: you could click the input area then click outside, it will become transparent.

This is a bug, thanks for your report. :)

**Comment by rayman89** [comment]
BTW maybe would be nice to have confirmation when clicking on the X to delete the note in case it was accidental.

**Comment by wildskyf** [comment]
> Thank you for the workaround BTW maybe would be nice to have confirmation when clicking on the X to delete the note in case it was accidental.

good idea. It will be implemented in the next version :)
(And I will open another issue to tracking it.)

**Comment by grahamperrin** [comment]
Not reproducible with version 1.15.0.

**Comment by rayman89** [comment]
This has been fixed for a long time @grahamperrin I guess he forgot to close it.
