### ISSUE TITLE
drag to move

### ISSUE THREAD

**Issue by rayman89** [wildskyf/pageMemo#15]
I've been using your addon more and more and noticed that the click to move thing on the notes often glitches if you move the mouse a little bit more faster than slow. Could the feature be replaced with drag and drop or be more polished?

**Comment by wildskyf** [comment]
I also think drag and drop is easier to use.(but not that easy to implement) 
I choose to click to move is because it is easy to implement, and at that time I just want a way to move memo.

Now I think it is the time to implement drag and drop. :)
It will be implemented in the next version!
